### PR TITLE
Esnext it all

### PR DESCRIPTION
**Pull request by robin-drexler**
@filtercake @teamrandom/member  PTAL :D

### CODE REVIEW

**Comment by filtercake** [comment]
lgtm – since i do not really speak js though, no idea. i mean, what does "looks good to me" actually mean anyways? and will our search for meaning take us anywhere? is it really a search? don't we want to *find*? why not? what is holding us back? and from what? are we actually being saved, not held back? because the truth would be unbearable? the utter futility of an imagined, meaningless life within a simulation designed to proof happiness does exist the first place and is itself a concept based on duality and **EXISTS ONLY IN COMPARISON TO SADNESS?!**

tune in again tomorrow, when none of these questions will be answered. we will instead test how well snickers do as... wait for it... BLOCKCHAIN!!!\*

image

\* no drugs where harmed in writing this comment**

\*\* drugs not available in all areas

**Comment by klyrr** [comment]
lambda function!

**Comment by robin-drexler** [comment]
Can somebody merge asap pls? This is on the critical path of a very important project.
I've opened this PR already a day ago!1! 😠

**Comment by filtercake** [comment]
I would but... too many choices...

0eb9240e-170a-497a-b8bf-98cc7c277f9b

**Comment by robin-drexler** [comment]
STOP! I need to fix readme first. That was close

**Comment by robin-drexler** [comment]
Done. GO FOR THE REBASE!

**Comment by klyrr** [comment]
No! Wait!

**Comment by klyrr** [comment]
You intended with spaces instead of tabs. Before we can merge this we have to discuss what to do about that.
I wasn't asked about that!!!!11

**Comment by robin-drexler** [comment]
Prettier made it. Prettier is our new formatting overlord. It's good to
merge, eh rebase. Trust me!

**Comment by filtercake** [comment]
Why don’t we go with standard.js? It has its name for a reason, ok?!

**Comment by robin-drexler** [comment]
You're right. Let's still merge. We'll fix this temporary flaw in our next
refactoring sprint. I promise.

**Comment by klyrr** [comment]
No! You can't do that. You always want to have the last word!

**Comment by filtercake** [comment]
I emailed atlassian about a jira setup. We really need to get some proper decision making process in place!

**Comment by robin-drexler** [comment]
it's 2018 already and it still has not been merged!1!

**Comment by klyrr** [comment]
I would if I could. But apparently I am not trusted enough to have *write access*...

**Comment by afknapping** [comment]
you very much trusted enough and I thought you had write access...

i don't get at all how the whole permissions/roles/teams geraffel works in github ¯\\\_(ツ)\_/¯

**Pull request merged**
